[2023-01-02 19:10:12,094] - [INFO] - [137c8804-66a1-47b0-8278-035076b870b9] - [create_accounts] - [<module>] - Attempting to Register 11 Email(s) with ESPN
[2023-01-02 19:10:13,973] - [ERROR] - [b7700175-c7df-4b4a-949d-34128db79703] - [create_accounts] - [register_wrapper] - UNKNOWN - Failed to Register Email: alecjmasterson+1204@gmail.com
[2023-01-02 19:10:14,623] - [ERROR] - [15296a4c-4702-44a0-a37a-b4c40f460689] - [create_accounts] - [register_wrapper] - UNKNOWN - Failed to Register Email: alecjmasterson+1200@gmail.com
[2023-01-02 19:10:14,635] - [ERROR] - [b7700175-c7df-4b4a-949d-34128db79703] - [create_accounts] - [register_wrapper] - UNKNOWN - Failed to Register Email: alecjmasterson+1208@gmail.com
[2023-01-02 19:10:14,646] - [ERROR] - [75e39d72-265d-44ad-ab73-bdcc9ab5ff92] - [create_accounts] - [register_wrapper] - UNKNOWN - Failed to Register Email: alecjmasterson+1201@gmail.com
[2023-01-02 19:10:15,049] - [ERROR] - [96f44c5d-9f99-42f9-8a8c-84ab41785427] - [create_accounts] - [register_wrapper] - UNKNOWN - Failed to Register Email: alecjmasterson+1202@gmail.com
[2023-01-02 19:10:15,204] - [ERROR] - [15296a4c-4702-44a0-a37a-b4c40f460689] - [create_accounts] - [register_wrapper] - UNKNOWN - Failed to Register Email: alecjmasterson+1209@gmail.com
[2023-01-02 19:10:15,210] - [ERROR] - [b7700175-c7df-4b4a-949d-34128db79703] - [create_accounts] - [register_wrapper] - UNKNOWN - Failed to Register Email: alecjmasterson+1210@gmail.com
[2023-01-02 19:10:15,226] - [ERROR] - [b3f8d4c8-48ff-4dbd-ad53-cb8e1d5764e4] - [create_accounts] - [register_wrapper] - UNKNOWN - Failed to Register Email: alecjmasterson+1205@gmail.com
[2023-01-02 19:10:15,264] - [ERROR] - [da331df0-4494-4d91-9404-aa01e93f215f] - [create_accounts] - [register_wrapper] - UNKNOWN - Failed to Register Email: alecjmasterson+1203@gmail.com
[2023-01-02 19:10:15,964] - [ERROR] - [ca0ac7f4-2191-4ebc-9bd7-51904e2706f1] - [create_accounts] - [register_wrapper] - UNKNOWN - Failed to Register Email: alecjmasterson+1207@gmail.com
[2023-01-02 19:10:16,193] - [ERROR] - [85151651-d195-4717-8519-bcf24cc56f7e] - [create_accounts] - [register_wrapper] - UNKNOWN - Failed to Register Email: alecjmasterson+1206@gmail.com
[2023-01-02 19:10:16,296] - [INFO] - [137c8804-66a1-47b0-8278-035076b870b9] - [create_accounts] - [main] - ['1200', '1201', '1202', '1203', '1204', '1205', '1206', '1207', '1208', '1209', '1210']
[2023-01-02 19:11:12,191] - [INFO] - [347fe2a2-8a7c-45da-b000-f58105ccf841] - [create_accounts] - [<module>] - Attempting to Register 11 Email(s) with ESPN
[2023-01-02 19:11:13,876] - [ERROR] - [347fe2a2-8a7c-45da-b000-f58105ccf841] - [__init__] - [exception_handler] - Uncaught Exception
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 20, in register_wrapper
    with ESPN(email) as espn:
  File "/Users/alecmasterson/Documents/march_madness/ESPN.py", line 42, in __enter__
    self.__Driver = webdriver.Chrome(service_args=["--headless", "--log-level=3"])
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 106, in start
    self.assert_process_still_running()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 119, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 1

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 72, in <module>
    main(emails)
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 51, in main
    failures: List[tuple] = [result for result in [future.result() for future in futures] if not result[0]]
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 51, in <listcomp>
    failures: List[tuple] = [result for result in [future.result() for future in futures] if not result[0]]
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 1

[2023-01-02 19:11:55,317] - [INFO] - [bf0b1558-cbfe-49f7-9d29-009ac795e381] - [create_accounts] - [<module>] - Attempting to Register 1 Email(s) with ESPN
[2023-01-02 19:11:56,091] - [ERROR] - [bf0b1558-cbfe-49f7-9d29-009ac795e381] - [__init__] - [exception_handler] - Uncaught Exception
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 20, in register_wrapper
    with ESPN(email) as espn:
  File "/Users/alecmasterson/Documents/march_madness/ESPN.py", line 42, in __enter__
    self.__Driver = webdriver.Chrome(service_args=["--headless", "--log-level=3"])
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 106, in start
    self.assert_process_still_running()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 119, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 1

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 72, in <module>
    main(emails)
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 51, in main
    failures: List[tuple] = [result for result in [future.result() for future in futures] if not result[0]]
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 51, in <listcomp>
    failures: List[tuple] = [result for result in [future.result() for future in futures] if not result[0]]
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 1

[2023-01-02 19:15:54,739] - [INFO] - [ee56e000-39e4-4cab-a38d-20e0a5486412] - [create_accounts] - [<module>] - Attempting to Register 1 Email(s) with ESPN
[2023-01-02 19:15:55,562] - [ERROR] - [ee56e000-39e4-4cab-a38d-20e0a5486412] - [__init__] - [exception_handler] - Uncaught Exception
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 20, in register_wrapper
    with ESPN(email) as espn:
  File "/Users/alecmasterson/Documents/march_madness/ESPN.py", line 45, in __enter__
    self.__Driver = webdriver.Chrome(service_args=["--headless", "--log-level=3"])
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 106, in start
    self.assert_process_still_running()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 119, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 1

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 72, in <module>
    main(emails)
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 51, in main
    failures: List[tuple] = [result for result in [future.result() for future in futures] if not result[0]]
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 51, in <listcomp>
    failures: List[tuple] = [result for result in [future.result() for future in futures] if not result[0]]
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 1

[2023-01-02 19:16:18,712] - [INFO] - [6b4e0d8a-12b0-48f7-9257-7b54f4cf19af] - [create_accounts] - [<module>] - Attempting to Register 1 Email(s) with ESPN
[2023-01-02 19:16:33,240] - [WARNING] - [fbeaa1f1-0a10-4f40-ae90-865adda28244] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, 
<traceback object at 0x7f9c227a6140>
[2023-01-02 19:16:33,314] - [WARNING] - [fbeaa1f1-0a10-4f40-ae90-865adda28244] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1201@gmail.com
[2023-01-02 19:16:33,362] - [INFO] - [6b4e0d8a-12b0-48f7-9257-7b54f4cf19af] - [create_accounts] - [main] - []
[2023-01-02 19:16:37,128] - [INFO] - [a5e58213-f22a-4ec0-9889-91f722290fc3] - [create_accounts] - [<module>] - Attempting to Register 1 Email(s) with ESPN
[2023-01-02 19:16:44,690] - [WARNING] - [e5e17ea8-8cc6-4363-bfba-5c82dce5fa47] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, 
<traceback object at 0x7fdf5f7c3480>
[2023-01-02 19:16:44,808] - [ERROR] - [a5e58213-f22a-4ec0-9889-91f722290fc3] - [__init__] - [exception_handler] - Uncaught Exception
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 21, in register_wrapper
    espn.register()
  File "/Users/alecmasterson/Documents/march_madness/ESPN.py", line 135, in register
    raise EmailTakenException
exceptions.EmailTakenException.EmailTakenException
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 72, in <module>
    main(emails)
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 51, in main
    failures: List[tuple] = [result for result in [future.result() for future in futures] if not result[0]]
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 51, in <listcomp>
    failures: List[tuple] = [result for result in [future.result() for future in futures] if not result[0]]
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
exceptions.EmailTakenException.EmailTakenException
[2023-01-02 19:18:18,694] - [INFO] - [11d9c5ba-b67c-4130-a3bf-2dbfef148f8a] - [create_accounts] - [<module>] - Attempting to Register 1 Email(s) with ESPN
[2023-01-02 19:18:31,351] - [WARNING] - [a0aa9285-1ac8-4209-ae99-a642c822caf3] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, 
<traceback object at 0x7f77e8d0ba00>
[2023-01-02 19:18:31,424] - [WARNING] - [a0aa9285-1ac8-4209-ae99-a642c822caf3] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1202@gmail.com
[2023-01-02 19:18:31,466] - [INFO] - [11d9c5ba-b67c-4130-a3bf-2dbfef148f8a] - [create_accounts] - [main] - []
[2023-01-02 19:19:07,012] - [INFO] - [23dadc6e-257e-4191-9af4-f056e3dbc996] - [create_accounts] - [<module>] - Attempting to Register 1 Email(s) with ESPN
[2023-01-02 19:19:20,109] - [WARNING] - [95fc2b5d-e7db-4364-8d1b-0ab0787ecd6a] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, 
<traceback object at 0x7f815d764700>
[2023-01-02 19:19:20,182] - [WARNING] - [95fc2b5d-e7db-4364-8d1b-0ab0787ecd6a] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1203@gmail.com
[2023-01-02 19:19:20,222] - [INFO] - [23dadc6e-257e-4191-9af4-f056e3dbc996] - [create_accounts] - [main] - []
[2023-01-02 19:20:09,843] - [INFO] - [a27a4600-4ca0-408c-8200-bfb75633d22e] - [create_accounts] - [<module>] - Attempting to Register 1 Email(s) with ESPN
[2023-01-02 19:20:14,764] - [WARNING] - [149b78f6-4716-4e12-9bae-45299292b1b2] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'exceptions.EmailTakenException.EmailTakenException'> - 
<traceback object at 0x7fe9b2f777c0>
[2023-01-02 19:20:14,881] - [ERROR] - [a27a4600-4ca0-408c-8200-bfb75633d22e] - [__init__] - [exception_handler] - Uncaught Exception
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 21, in register_wrapper
    espn.register()
  File "/Users/alecmasterson/Documents/march_madness/ESPN.py", line 135, in register
    raise EmailTakenException
exceptions.EmailTakenException.EmailTakenException
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 72, in <module>
    main(emails)
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 51, in main
    failures: List[tuple] = [result for result in [future.result() for future in futures] if not result[0]]
  File "/Users/alecmasterson/Documents/march_madness/create_accounts.py", line 51, in <listcomp>
    failures: List[tuple] = [result for result in [future.result() for future in futures] if not result[0]]
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
exceptions.EmailTakenException.EmailTakenException
[2023-01-02 19:20:42,113] - [INFO] - [6315e394-66bc-418a-bd82-207f56eb730f] - [create_accounts] - [<module>] - Attempting to Register 1 Email(s) with ESPN
[2023-01-02 19:20:55,138] - [WARNING] - [8aed126a-cf98-46ee-bd37-6f56f8f27f0c] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'exceptions.EmailTakenException.EmailTakenException'> - 
<traceback object at 0x7f894d7a2a80>
[2023-01-02 19:20:55,210] - [WARNING] - [8aed126a-cf98-46ee-bd37-6f56f8f27f0c] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1204@gmail.com
[2023-01-02 19:20:55,253] - [INFO] - [6315e394-66bc-418a-bd82-207f56eb730f] - [create_accounts] - [main] - []
[2023-01-02 19:22:21,427] - [INFO] - [7d6eab71-16b9-442e-b0cc-b8d21af23e64] - [create_accounts] - [<module>] - Attempting to Register 1 Email(s) with ESPN
[2023-01-02 19:22:34,792] - [WARNING] - [1c39e133-25f4-42f1-8807-8846a117e5aa] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'exceptions.EmailTakenException.EmailTakenException'> - 
<traceback object at 0x7fe1087c5fc0>
[2023-01-02 19:22:34,865] - [WARNING] - [1c39e133-25f4-42f1-8807-8846a117e5aa] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1205@gmail.com
[2023-01-02 19:22:34,915] - [INFO] - [7d6eab71-16b9-442e-b0cc-b8d21af23e64] - [create_accounts] - [main] - []
[2023-01-02 19:22:58,086] - [INFO] - [a0dad0f5-6b00-4ef8-9456-1a3c1e22a2e1] - [create_accounts] - [<module>] - Attempting to Register 1 Email(s) with ESPN
[2023-01-02 19:23:15,536] - [WARNING] - [f427dcbb-2ddf-42f5-a9c1-acff7bc35851] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'exceptions.EmailTakenException.EmailTakenException'> - 
<traceback object at 0x7f9762f9b440>
[2023-01-02 19:23:15,610] - [WARNING] - [f427dcbb-2ddf-42f5-a9c1-acff7bc35851] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1211@gmail.com
[2023-01-02 19:23:15,653] - [INFO] - [a0dad0f5-6b00-4ef8-9456-1a3c1e22a2e1] - [create_accounts] - [main] - []
[2023-01-02 19:23:42,438] - [INFO] - [f02600db-5a3b-4aa9-ace4-16e84c0856ea] - [create_accounts] - [<module>] - Attempting to Register 1 Email(s) with ESPN
[2023-01-02 19:23:55,422] - [WARNING] - [b7cfd8c9-8e21-4e23-8444-04f86154a4a2] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'exceptions.EmailTakenException.EmailTakenException'> - 
<traceback object at 0x7fd4f87a2900>
[2023-01-02 19:23:55,495] - [WARNING] - [b7cfd8c9-8e21-4e23-8444-04f86154a4a2] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1210@gmail.com
[2023-01-02 19:23:55,538] - [INFO] - [f02600db-5a3b-4aa9-ace4-16e84c0856ea] - [create_accounts] - [main] - []
[2023-01-02 19:27:10,724] - [INFO] - [d240c9c3-454f-452e-b898-778303957a55] - [create_accounts] - [<module>] - Attempting to Register 1 Email(s) with ESPN
[2023-01-02 19:27:23,918] - [WARNING] - [02877e29-8325-4f72-8436-ea9fd3e337db] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'exceptions.EmailTakenException.EmailTakenException'> - 
<traceback object at 0x7f9c1c0d1780>
[2023-01-02 19:27:23,993] - [WARNING] - [02877e29-8325-4f72-8436-ea9fd3e337db] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1206@gmail.com
[2023-01-02 19:27:24,042] - [INFO] - [d240c9c3-454f-452e-b898-778303957a55] - [create_accounts] - [main] - []
[2023-01-02 19:27:40,441] - [INFO] - [60fc706f-d508-4a52-8619-1c2745187e48] - [create_accounts] - [<module>] - Attempting to Register 16 Email(s) with ESPN
[2023-01-02 19:27:47,839] - [WARNING] - [9a1c6444-9a0e-43de-b6fe-7d196e0fb35d] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'exceptions.EmailTakenException.EmailTakenException'> - 
<traceback object at 0x7fa4c7cc8b40>
[2023-01-02 19:27:47,925] - [WARNING] - [9a1c6444-9a0e-43de-b6fe-7d196e0fb35d] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1200@gmail.com
[2023-01-02 19:27:48,658] - [WARNING] - [da2fc3ab-e538-417e-a39c-926c331c124b] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'exceptions.EmailTakenException.EmailTakenException'> - 
<traceback object at 0x7fdec0992700>
[2023-01-02 19:27:48,748] - [WARNING] - [da2fc3ab-e538-417e-a39c-926c331c124b] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1206@gmail.com
[2023-01-02 19:27:53,666] - [WARNING] - [b0099ebc-8d80-4855-8284-cfa4de6b2eff] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'selenium.common.exceptions.NoSuchElementException'> - Message: None

<traceback object at 0x7f94037c5f80>
[2023-01-02 19:27:53,786] - [ERROR] - [b0099ebc-8d80-4855-8284-cfa4de6b2eff] - [create_accounts] - [register_wrapper] - NOSUCHELEMENT - Failed to Register Email: alecjmasterson+1202@gmail.com
[2023-01-02 19:27:54,022] - [WARNING] - [841c10b1-4ccd-48ee-81a6-8a1d77ecb9b5] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'selenium.common.exceptions.NoSuchElementException'> - Message: None

<traceback object at 0x7fb817fc4380>
[2023-01-02 19:27:54,097] - [ERROR] - [841c10b1-4ccd-48ee-81a6-8a1d77ecb9b5] - [create_accounts] - [register_wrapper] - NOSUCHELEMENT - Failed to Register Email: alecjmasterson+1201@gmail.com
[2023-01-02 19:27:57,402] - [WARNING] - [e0e55905-0090-4b5a-9ff3-e9505df9c15d] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'exceptions.EmailTakenException.EmailTakenException'> - 
<traceback object at 0x7f8c73e35e00>
[2023-01-02 19:27:57,495] - [WARNING] - [e0e55905-0090-4b5a-9ff3-e9505df9c15d] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1205@gmail.com
[2023-01-02 19:27:58,819] - [WARNING] - [b0099ebc-8d80-4855-8284-cfa4de6b2eff] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'exceptions.EmailTakenException.EmailTakenException'> - 
<traceback object at 0x7f9403635400>
[2023-01-02 19:27:58,894] - [WARNING] - [b0099ebc-8d80-4855-8284-cfa4de6b2eff] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1210@gmail.com
[2023-01-02 19:27:59,514] - [WARNING] - [841c10b1-4ccd-48ee-81a6-8a1d77ecb9b5] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'exceptions.EmailTakenException.EmailTakenException'> - 
<traceback object at 0x7fb817fb0b80>
[2023-01-02 19:27:59,590] - [WARNING] - [841c10b1-4ccd-48ee-81a6-8a1d77ecb9b5] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1211@gmail.com
[2023-01-02 19:28:04,182] - [WARNING] - [5fc5d576-c56d-4ead-91b7-95b54ad676cd] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'selenium.common.exceptions.NoSuchElementException'> - Message: None

<traceback object at 0x7fe197fb8840>
[2023-01-02 19:28:04,258] - [ERROR] - [5fc5d576-c56d-4ead-91b7-95b54ad676cd] - [create_accounts] - [register_wrapper] - NOSUCHELEMENT - Failed to Register Email: alecjmasterson+1204@gmail.com
[2023-01-02 19:28:04,318] - [WARNING] - [eef48394-7fda-4759-8a26-6aa24120f681] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'selenium.common.exceptions.NoSuchElementException'> - Message: None

<traceback object at 0x7fa3cdfc2740>
[2023-01-02 19:28:04,395] - [ERROR] - [eef48394-7fda-4759-8a26-6aa24120f681] - [create_accounts] - [register_wrapper] - NOSUCHELEMENT - Failed to Register Email: alecjmasterson+1203@gmail.com
[2023-01-02 19:28:10,657] - [WARNING] - [da2fc3ab-e538-417e-a39c-926c331c124b] - [ESPN] - [__exit__] - Selenium Driver failed to Exit Properly, <class 'selenium.common.exceptions.NoSuchElementException'> - Message: None

<traceback object at 0x7fdec0fb8a40>
[2023-01-02 19:28:10,729] - [ERROR] - [da2fc3ab-e538-417e-a39c-926c331c124b] - [create_accounts] - [register_wrapper] - NOSUCHELEMENT - Failed to Register Email: alecjmasterson+1209@gmail.com
[2023-01-02 19:28:27,094] - [INFO] - [60fc706f-d508-4a52-8619-1c2745187e48] - [create_accounts] - [main] - ['1201', '1202', '1203', '1204', '1209']
[2023-01-02 19:32:31,789] - [INFO] - [01beade6-39f4-44f2-be85-e8fa7e96a7ac] - [create_accounts] - [<module>] - Attempting to Register 5 Email(s) with ESPN
[2023-01-02 19:32:37,387] - [WARNING] - [b6e6bef3-4bce-4e50-97d6-cf03099e6a6a] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1204@gmail.com
[2023-01-02 19:32:47,410] - [WARNING] - [537f48e7-0569-417a-b0f7-7d940eff4759] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1202@gmail.com
[2023-01-02 19:32:47,506] - [WARNING] - [3f3758ad-7d72-46bb-93e0-6fc2770eb190] - [create_accounts] - [register_wrapper] - Email Taken: alecjmasterson+1201@gmail.com
[2023-01-02 19:32:54,469] - [ERROR] - [73b4d896-09d8-4203-8831-f252e539d192] - [create_accounts] - [register_wrapper] - NOSUCHELEMENT - Failed to Register Email: alecjmasterson+1209@gmail.com
[2023-01-02 19:32:54,514] - [ERROR] - [e775bc4c-79af-4c92-b5e3-99ce31259afd] - [create_accounts] - [register_wrapper] - NOSUCHELEMENT - Failed to Register Email: alecjmasterson+1203@gmail.com
[2023-01-02 19:32:54,603] - [INFO] - [01beade6-39f4-44f2-be85-e8fa7e96a7ac] - [create_accounts] - [main] - ['1203', '1209']
[2023-01-02 21:00:27,852] - [INFO] - [504d0fd2-b99c-4475-a2fb-92b09ee86051] - [create_accounts] - [<module>] - Attempting to Register 2 Email(s) with ESPN
[2023-01-02 21:00:37,198] - [INFO] - [504d0fd2-b99c-4475-a2fb-92b09ee86051] - [create_accounts] - [main] - []
[2023-01-02 21:00:58,296] - [INFO] - [1ae656e2-5b62-444f-a084-ba549abd0d9a] - [create_accounts] - [<module>] - Attempting to Register 51 Email(s) with ESPN
[2023-01-02 21:02:34,000] - [INFO] - [1ae656e2-5b62-444f-a084-ba549abd0d9a] - [create_accounts] - [main] - []
[2023-01-02 21:03:22,619] - [INFO] - [2779b852-ca8e-425a-ad51-b6b175c62dc6] - [create_accounts] - [<module>] - Attempting to Register 251 Email(s) with ESPN
[2023-01-02 21:12:31,127] - [INFO] - [2779b852-ca8e-425a-ad51-b6b175c62dc6] - [create_accounts] - [main] - ['1253', '1281', '1288', '1298', '1385', '1391', '1392', '1393', '1396', '1397', '1399', '1400', '1401', '1402', '1403', '1405']
